#!/bin/bash

set -eu # -x for verbose logging to juju debug-log
juju-log "Starting install of Zabbix Agent"

charmdir=${PWD}
srcdir=${PWD}/src

add-apt-repository ppa:charmers/charm-helpers > /dev/null
apt-get -qq update && apt-get -qq -y upgrade > /dev/null

apt-get -qq -y install pwgen mailutils sysstat charm-helper-sh rsync nfs-common git-core mktemp default-jdk make gcc > /dev/null

juju-log "setup zabbix user and group"
if [ "$(grep -c zabbix /etc/group)" -lt "1" ] ; then
  groupadd -f zabbix
fi

if [ "$(grep -c zabbix /etc/passwd)" -lt "1" ] ; then
  useradd -m -g zabbix zabbix
fi

juju-log "extract zabbix source"
mkdir -p /tmp/zabbix-src
cd /tmp/zabbix-src

tar zxf ${srcdir}/zabbix-2.0.5.tar.gz
cd zabbix-2.0.5

juju-log "configure zabbix source"
./configure --enable-agent > /dev/null

juju-log "make zabbix source"
make install > /dev/null

juju-log "finished install of zabbix agent"
cd ${charmdir}
